name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ secrets.DOCKER_REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          docker build --pull -t ${{ secrets.DOCKER_REGISTRY_IMAGE }} .
          docker push ${{ secrets.DOCKER_REGISTRY_IMAGE }}
