name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build --pull -t https://hub.docker.com/repository/docker/andreiionut1411/just_testing .
          docker push https://hub.docker.com/repository/docker/andreiionut1411/just_testing
